### ISSUE TITLE
Fix the child key issue in the JS console

### ISSUE THREAD

**Issue by wpscholar** [newfold-labs/wp-module-help-center#14]
We need to remove the wrapper around the `<AlgoliaSearchResult>` component so the `key` is set on the base element in the `.map()`. This will resolve the `Warning: Each child in a list should have a unique "key" prop.` error in the console.

https://github.com/newfold-labs/wp-module-help-center/blob/trunk/src/components/SearchResults.js#L161-L174

**Comment by amartya-dev** [comment]
This was fixed in #13
